@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

# POST http://{{host}}/login/ HTTP/1.1
# Content-Type: {{contentType}}

# {
#     "name": "Michael",
#     "email": "newAdminTEST@journeymxn.com",
#     "age": 23,
#     "password": "ABC9999"
# }
POST http://{{host}}/submitForm/ HTTP/1.1
Content-Type: {{contentType}}

{
    
}