const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Student = new Schema({
  id: {
    //Should be Autogenerated using ObjectId()
    type: Number,
  },
  zipcode: {
    type: Number,
    required: true
  },
  quizResponses: 
  //Array of 'QuestionResponse' objects
  [{
    type: Schema.Types.ObjectId,
    ref: 'QuestionResponse'
  }]
});

module.exports = Student = mongoose.model('Student', Student);